### PR TITLE
Only unique books append to array, Modal modifications too

### PR DESCRIPTION
**Pull request by howilliam**
made adjustments to the function to only append unique books, 

modal content is also emptied everytime it is clicked, this avoids the same content being pushed into the modal

### CODE REVIEW

**Review by blooshroo — APPROVED** [review]
From what I can tell, looks good! Thanks William!

**Review by shkendi — COMMENTED** [review]
It looks good to me William, thanks.

**Review by Pine-Box — APPROVED** [review]
ok

**Review by shkendi — COMMENTED** [review]
Looks ok!

**Pull request merged**
